# Generated by Django 5.0.4 on 2024-05-02 06:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField()),
                ('canceled_at', models.DateTimeField()),
                ('livestock_number', models.IntegerField()),
                ('permit_number', models.CharField(blank=True, max_length=250, null=True)),
                ('permit_typec', models.CharField(blank=True, choices=[('TRANSFER', 'Transfer'), ('SELLING', 'Selling')], max_length=250, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PERMITED', 'Permited'), ('CANCELED', 'Canceled')], max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permit_table',
            },
        ),
    ]
