# Generated by Django 5.0.4 on 2024-05-02 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='canceled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_canceled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_request_permit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permit',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_issued_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
